# Generated by Django 4.2 on 2023-04-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placememory',
            old_name='city',
            new_name='place',
        ),
    ]
